### ISSUE TITLE
Create and implement _data variables for more cohesive Documentation

### ISSUE THREAD

**Issue by bnvk** [QubesOS/qubesos.github.io#3]
As a new user of any software project, a frustrating experience I encounter is stale documentation and lack of cohesive terminology as these factors lead to more challenging (than it could be) and sometimes show-stoping confusion. 

Luckily, with Qubes, I have not been completely stumped by anything, yet, but I still would like to help improve the documentation for less technically inclined users.

**Example 1** 

While configuring my Qubes to to have a TorVM via [this documentation](https://www.qubes-os.org/doc/UserDoc/TorVM/) the page references the TemplateVM  `fedora-20-x64` which is outdated as a fresh install creates TemplateVM called `fedora-21`

**Example 2**

Additionally, throughout the docs the referencing of the different type of VMs changes quite a bit. For example, on the TorVM page, the following references to TemplateVM are used:

```
template
template vm
templateVM
```

These are all tiny & easy mistakes to make as a human writing natural language documentation. Thus, I propose adding variables to a file like `_data/terms.yml` so that in the docs, the writer would type `{{terms.vm_template}}` or `{{terms.vm_template_name}}` which Jekyll would render as `TemplateVM` and `fedora-21` respectively, upon building the site.

I think this change will help by keeping things current and more cohesive. I'm happy to do this tedious task if it is welcomed (and will be accepted) as it will help me get more familiar with Qubes and contribute back to the community!

**Comment by marmarek** [comment]
Please, add this to qubes-issues repository - where we keep all the issues (for all the parts: code, documentation, website). I see qubesos.github.io is one place where we've forgotten to disable issues module...

Generally I like your idea, but lets discuss details after migrating issue.
